const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const tabs=$$(".game-tab"),panels=$$(".game-panel");
tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));panels.forEach(p=>p.classList.remove("active"));tab.classList.add("active");$("#"+tab.dataset.game+"-panel").classList.add("active");}));

(()=>{const c=$("#shooter-canvas"),ctx=c.getContext("2d"),scoreEl=$("#shooter-score"),timeEl=$("#shooter-time"),msg=$("#shooter-message"),start=$("#shooter-start");let score=0,time=30,running=false,timer,raf,target=null;const rand=(a,b)=>Math.random()*(b-a)+a;
function spawn(){const r=rand(18,30);target={x:rand(r+8,c.width-r-8),y:rand(65,c.height-r-8),r,dx:rand(-70,70),dy:rand(-55,55),pulse:Math.random()*6}}
function draw(t){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#020711";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="rgba(82,232,255,.07)";for(let x=0;x<c.width;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.stroke()}for(let y=0;y<c.height;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke()}if(target){target.x+=target.dx/60;target.y+=target.dy/60;if(target.x<target.r||target.x>c.width-target.r)target.dx*=-1;if(target.y<target.r+45||target.y>c.height-target.r)target.dy*=-1;ctx.shadowBlur=12+Math.sin(t/120+target.pulse)*4;ctx.shadowColor="#52e8ff";ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,Math.PI*2);ctx.fillStyle="#0a2636";ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(target.x,target.y,target.r*.72,0,Math.PI*2);ctx.strokeStyle="#52e8ff";ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(target.x,target.y,target.r*.22,0,Math.PI*2);ctx.fillStyle="#ff4f9a";ctx.fill()}if(running)raf=requestAnimationFrame(draw)}
function end(){running=false;clearInterval(timer);cancelAnimationFrame(raf);msg.textContent="SCORE: "+score+" • PLAY AGAIN";msg.classList.remove("hidden");start.textContent="PLAY AGAIN"}
function begin(){score=0;time=30;running=true;scoreEl.textContent=0;timeEl.textContent=30;msg.classList.add("hidden");start.textContent="RESTART";spawn();clearInterval(timer);timer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0)end()},1000);cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
c.addEventListener("pointerdown",e=>{if(!running||!target)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;if(Math.hypot(x-target.x,y-target.y)<=target.r){score++;scoreEl.textContent=score;spawn()}});start.addEventListener("click",begin);draw(0)})();

(()=>{const c=$("#racing-canvas"),ctx=c.getContext("2d"),scoreEl=$("#racing-score"),timeEl=$("#racing-time"),msg=$("#racing-message"),start=$("#racing-start"),left=$("#race-left"),right=$("#race-right");let running=false,playerX=180,score=0,time=30,traffic=[],last=0,timer,raf,keys={};const laneX=l=>115+l*65;
function spawn(){traffic.push({x:laneX(Math.floor(Math.random()*3)),y:-70,w:42,h:70,s:180+Math.random()*100})}
function car(x,y,w,h,color){ctx.shadowBlur=14;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x-w/2,y-h/2,w,h,9);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#06101d";ctx.fillRect(x-w*.32,y-h*.25,w*.64,h*.22);ctx.fillRect(x-w*.32,y+h*.03,w*.64,h*.22)}
function road(){ctx.fillStyle="#050916";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#0b1328";ctx.fillRect(55,0,250,c.height);ctx.strokeStyle="rgba(82,232,255,.25)";ctx.lineWidth=3;ctx.strokeRect(56,0,248,c.height);ctx.strokeStyle="rgba(255,255,255,.2)";ctx.lineWidth=4;ctx.setLineDash([28,25]);ctx.lineDashOffset=-(performance.now()/8%53);[138,203,268].forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.stroke()});ctx.setLineDash([])}
function update(dt){if(keys.ArrowLeft||keys.a)playerX-=260*dt;if(keys.ArrowRight||keys.d)playerX+=260*dt;playerX=Math.max(80,Math.min(280,playerX));traffic.forEach(v=>v.y+=v.s*dt);traffic=traffic.filter(v=>v.y<570);for(const v of traffic)if(Math.abs(v.x-playerX)<36&&Math.abs(v.y-450)<55){end();return}}
function draw(){road();traffic.forEach(v=>car(v.x,v.y,v.w,v.h,"#ff4f9a"));car(playerX,450,44,76,"#52e8ff");if(running){const now=performance.now(),dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);score++;scoreEl.textContent=Math.floor(score/6);raf=requestAnimationFrame(draw)}}
function end(){running=false;clearInterval(timer);cancelAnimationFrame(raf);msg.textContent="CRASH! • SCORE: "+Math.floor(score/6);msg.classList.remove("hidden");start.textContent="RACE AGAIN"}
function begin(){running=true;score=0;time=30;playerX=180;traffic=[];scoreEl.textContent=0;timeEl.textContent=30;msg.classList.add("hidden");start.textContent="RESTART";clearInterval(timer);timer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0)end()},1000);const sp=setInterval(()=>{if(!running){clearInterval(sp);return}spawn()},700);last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key==="ArrowLeft"||e.key==="ArrowRight")e.preventDefault()});addEventListener("keyup",e=>keys[e.key]=false);const press=(k,v)=>()=>keys[k]=v;left.addEventListener("pointerdown",press("ArrowLeft",true));left.addEventListener("pointerup",press("ArrowLeft",false));left.addEventListener("pointerleave",press("ArrowLeft",false));right.addEventListener("pointerdown",press("ArrowRight",true));right.addEventListener("pointerup",press("ArrowRight",false));right.addEventListener("pointerleave",press("ArrowRight",false));start.addEventListener("click",begin);draw()})();

(()=>{const board=$("#puzzle-board"),movesEl=$("#puzzle-moves"),timeEl=$("#puzzle-time"),start=$("#puzzle-new");let tiles=[],moves=0,time=0,timer;
function solved(){return tiles.every((v,i)=>v===(i===15?0:i+1))}
function shuffle(){tiles=[...Array(16)].map((_,i)=>i);let blank=15,prev=-1;for(let i=0;i<350;i++){const opts=[blank-1,blank+1,blank-4,blank+4].filter(n=>n>=0&&n<16&&!(blank%4===0&&n===blank-1)&&!(blank%4===3&&n===blank+1)&&n!==prev);const n=opts[Math.floor(Math.random()*opts.length)];[tiles[blank],tiles[n]]=[tiles[n],tiles[blank]];prev=blank;blank=n}render()}
function render(){board.innerHTML="";tiles.forEach((v,i)=>{const b=document.createElement("button");b.className="puzzle-tile"+(v===0?" empty":"");b.textContent=v||"";b.setAttribute("aria-label",v?"Tile "+v:"Empty space");b.addEventListener("click",()=>move(i));board.appendChild(b)})}
function move(i){const blank=tiles.indexOf(0),sameRow=Math.floor(i/4)===Math.floor(blank/4),near=[blank-1,blank+1,blank-4,blank+4].includes(i)&&((i===blank-1||i===blank+1)?sameRow:true);if(!near)return;[tiles[i],tiles[blank]]=[tiles[blank],tiles[i]];moves++;movesEl.textContent=moves;render();if(solved()){clearInterval(timer);setTimeout(()=>alert("Solved in "+moves+" moves and "+time+" seconds!"),80)}}
function begin(){clearInterval(timer);moves=0;time=0;movesEl.textContent=0;timeEl.textContent=0;shuffle();timer=setInterval(()=>{time++;timeEl.textContent=time},1000)}
start.addEventListener("click",begin);begin()})();