const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const tabs=$$(".game-tab"),panels=$$(".game-panel");
tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));panels.forEach(p=>p.classList.remove("active"));tab.classList.add("active");$("#"+tab.dataset.game+"-panel").classList.add("active");}));

(()=>{const c=$("#shooter-canvas"),ctx=c.getContext("2d"),scoreEl=$("#shooter-score"),timeEl=$("#shooter-time"),msg=$("#shooter-message"),start=$("#shooter-start");let score=0,time=30,running=false,timer,raf,target=null;const rand=(a,b)=>Math.random()*(b-a)+a;
function spawn(){const r=rand(18,30);target={x:rand(r+8,c.width-r-8),y:rand(65,c.height-r-8),r,dx:rand(-70,70),dy:rand(-55,55),pulse:Math.random()*6}}
function draw(t){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#020711";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="rgba(82,232,255,.07)";for(let x=0;x<c.width;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.stroke()}for(let y=0;y<c.height;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke()}if(target){target.x+=target.dx/60;target.y+=target.dy/60;if(target.x<target.r||target.x>c.width-target.r)target.dx*=-1;if(target.y<target.r+45||target.y>c.height-target.r)target.dy*=-1;ctx.shadowBlur=12+Math.sin(t/120+target.pulse)*4;ctx.shadowColor="#52e8ff";ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,Math.PI*2);ctx.fillStyle="#0a2636";ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(target.x,target.y,target.r*.72,0,Math.PI*2);ctx.strokeStyle="#52e8ff";ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(target.x,target.y,target.r*.22,0,Math.PI*2);ctx.fillStyle="#ff4f9a";ctx.fill()}if(running)raf=requestAnimationFrame(draw)}
function end(){running=false;clearInterval(timer);cancelAnimationFrame(raf);msg.textContent="SCORE: "+score+" • PLAY AGAIN";msg.classList.remove("hidden");start.textContent="PLAY AGAIN"}
function begin(){score=0;time=30;running=true;scoreEl.textContent=0;timeEl.textContent=30;msg.classList.add("hidden");start.textContent="RESTART";spawn();clearInterval(timer);timer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0)end()},1000);cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
c.addEventListener("pointerdown",e=>{if(!running||!target)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;if(Math.hypot(x-target.x,y-target.y)<=target.r){score++;scoreEl.textContent=score;spawn()}});start.addEventListener("click",begin);draw(0)})();

(()=>{const c=$("#racing-canvas"),ctx=c.getContext("2d"),scoreEl=$("#racing-score"),highEl=$("#racing-high"),timeEl=$("#racing-time"),msg=$("#racing-message"),start=$("#racing-start"),left=$("#race-left"),right=$("#race-right");let running=false,playerX=180,score=0,time=30,traffic=[],last=0,timer,raf,spawnTimer,keys={};const laneX=l=>115+l*65;let high=Number(localStorage.getItem("henry_racing_high")||0);highEl.textContent=high;
function spawn(){traffic.push({x:laneX(Math.floor(Math.random()*3)),y:-75,w:40,h:68,s:205+Math.random()*110})}
function car(x,y,w,h,color,player=false){ctx.save();ctx.translate(x,y);ctx.shadowBlur=player?22:13;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,10);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=player?"#b9f7ff":"#1a1020";ctx.beginPath();ctx.roundRect(-w*.31,-h*.31,w*.62,h*.25,5);ctx.fill();ctx.beginPath();ctx.roundRect(-w*.31,h*.06,w*.62,h*.22,5);ctx.fill();ctx.fillStyle=player?"#07172b":"#ff6aab";ctx.fillRect(-w*.42,-h*.44,7,5);ctx.fillRect(w*.23,-h*.44,7,5);ctx.fillStyle="#070b15";ctx.fillRect(-w/2-3,-h*.28,5,17);ctx.fillRect(w/2-2,-h*.28,5,17);ctx.fillRect(-w/2-3,h*.12,5,17);ctx.fillRect(w/2-2,h*.12,5,17);ctx.restore()}
function road(){const g=ctx.createLinearGradient(0,0,0,c.height);g.addColorStop(0,"#0a1122");g.addColorStop(1,"#03050d");ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#101a31";ctx.beginPath();ctx.moveTo(78,0);ctx.lineTo(282,0);ctx.lineTo(322,c.height);ctx.lineTo(38,c.height);ctx.closePath();ctx.fill();ctx.strokeStyle="rgba(82,232,255,.3)";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(78,0);ctx.lineTo(38,c.height);ctx.moveTo(282,0);ctx.lineTo(322,c.height);ctx.stroke();ctx.strokeStyle="rgba(255,255,255,.24)";ctx.lineWidth=3;ctx.setLineDash([25,24]);ctx.lineDashOffset=-(performance.now()/7%49);[145,215].forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.stroke()});ctx.setLineDash([]);ctx.fillStyle="rgba(82,232,255,.07)";ctx.fillRect(78,0,204,30)}
function update(dt){if(keys.ArrowLeft||keys.a)playerX-=275*dt;if(keys.ArrowRight||keys.d)playerX+=275*dt;playerX=Math.max(64,Math.min(296,playerX));traffic.forEach(v=>v.y+=v.s*dt);traffic=traffic.filter(v=>v.y<590);for(const v of traffic)if(Math.abs(v.x-playerX)<34&&Math.abs(v.y-450)<52){end();return}}
function draw(){road();traffic.forEach(v=>car(v.x,v.y,v.w,v.h,"#ff4f9a"));car(playerX,450,46,80,"#52e8ff",true);if(running){const now=performance.now(),dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);score++;const current=Math.floor(score/6);scoreEl.textContent=current;if(current>high){high=current;highEl.textContent=high;highEl.classList.add("race-high-beat");setTimeout(()=>highEl.classList.remove("race-high-beat"),550);localStorage.setItem("henry_racing_high",high)}raf=requestAnimationFrame(draw)}}
function end(){running=false;clearInterval(timer);clearInterval(spawnTimer);cancelAnimationFrame(raf);const final=Math.floor(score/6);msg.textContent=final>=high&&final>0?"NEW HIGH SCORE!":"RACE OVER • SCORE: "+final;msg.classList.remove("hidden");start.textContent="RACE AGAIN"}
function begin(){running=true;score=0;time=30;playerX=180;traffic=[];scoreEl.textContent=0;timeEl.textContent=30;msg.classList.add("hidden");start.textContent="RESTART";clearInterval(timer);clearInterval(spawnTimer);timer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0)end()},1000);spawnTimer=setInterval(()=>{if(running)spawn()},650);last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key==="ArrowLeft"||e.key==="ArrowRight")e.preventDefault()});addEventListener("keyup",e=>keys[e.key]=false);const press=(k,v)=>()=>keys[k]=v;left.addEventListener("pointerdown",press("ArrowLeft",true));left.addEventListener("pointerup",press("ArrowLeft",false));left.addEventListener("pointerleave",press("ArrowLeft",false));right.addEventListener("pointerdown",press("ArrowRight",true));right.addEventListener("pointerup",press("ArrowRight",false));right.addEventListener("pointerleave",press("ArrowRight",false));start.addEventListener("click",begin);draw()})();

(()=>{const board=$("#puzzle-board"),movesEl=$("#puzzle-moves"),timeEl=$("#puzzle-time"),start=$("#puzzle-new");let tiles=[],moves=0,time=0,timer;
function solved(){return tiles.every((v,i)=>v===(i===15?0:i+1))}
function shuffle(){tiles=[...Array(16)].map((_,i)=>i);let blank=15,prev=-1;for(let i=0;i<350;i++){const opts=[blank-1,blank+1,blank-4,blank+4].filter(n=>n>=0&&n<16&&!(blank%4===0&&n===blank-1)&&!(blank%4===3&&n===blank+1)&&n!==prev);const n=opts[Math.floor(Math.random()*opts.length)];[tiles[blank],tiles[n]]=[tiles[n],tiles[blank]];prev=blank;blank=n}render()}
function render(){board.innerHTML="";tiles.forEach((v,i)=>{const b=document.createElement("button");b.className="puzzle-tile"+(v===0?" empty":"");b.textContent=v||"";b.setAttribute("aria-label",v?"Tile "+v:"Empty space");b.addEventListener("click",()=>move(i));board.appendChild(b)})}
function move(i){const blank=tiles.indexOf(0),sameRow=Math.floor(i/4)===Math.floor(blank/4),near=[blank-1,blank+1,blank-4,blank+4].includes(i)&&((i===blank-1||i===blank+1)?sameRow:true);if(!near)return;[tiles[i],tiles[blank]]=[tiles[blank],tiles[i]];moves++;movesEl.textContent=moves;render();if(solved()){clearInterval(timer);setTimeout(()=>alert("Solved in "+moves+" moves and "+time+" seconds!"),80)}}
function begin(){clearInterval(timer);moves=0;time=0;movesEl.textContent=0;timeEl.textContent=0;shuffle();timer=setInterval(()=>{time++;timeEl.textContent=time},1000)}
start.addEventListener("click",begin);begin()})();